site_name: Requisitos de Software

theme:
  name: windmill-dark

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - index.md
  - Engenharia de Requisitos: listas/engenharia_requisitos.md
  - Cenários e Léxicos: listas/cenarios_lexicos.md
  - Modelagem Ágil: listas/modelagem_agil.md
  - Perfil de Usuário e Personas: listas/perfil_personas.md
  - Priorização: listas/priorizacao.md
  - Rastreabilidade: listas/rastreabilidade.md
