site_name: Requisitos de Software

theme:
  name: material

nav:
  - index.md
  - Engenharia de Requisitos: listas/engenharia_requisitos.md
  - Cenários e Léxicos: listas/cenarios_lexicos.md
  - Modelagem Ágil: listas/modelagem_agil.md
  - Perfil de Usuário e Personas: listas/perfil_personas.md
  - Priorização: listas/priorizacao.md
  - Rastreabilidade: listas/rastreabilidade.md
  - Framework NFR: listas/nfr.md
