site_name: REQ - notes
copyright: 2022 Nicolas Souza
repo_name: REQ-notes
repo_url: https://github.com/nszchagas/REQ-notes

theme:
  name: material
  features:
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Light mode

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  - index.md
  - Engenharia de Requisitos: listas/engenharia_requisitos.md
  - Cenários e Léxicos: listas/cenarios_lexicos.md
  - Modelagem Ágil: listas/modelagem_agil.md
  - Perfil de Usuário e Personas: listas/perfil_personas.md
  - Priorização: listas/priorizacao.md
  - Rastreabilidade: listas/rastreabilidade.md
  - Framework NFR: listas/nfr.md
  - Verificação e Validação: listas/verificacao_validacao.md
